const productsData = [
  {
    id: 1,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 2,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 3,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 4,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "-",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 5,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 6,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 7,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 8,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "-",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 9,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 10,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 11,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 12,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "-",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 13,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 14,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 15,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 16,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "-",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 17,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 18,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 19,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 20,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "DSFSDF",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 21,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 22,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 23,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "Academie",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
  {
    id: 24,
    categoryName: "Эстетический уход",
    subcategory: "Очищение",
    brand: "24elem",
    product: "Гоммаж с кремом и витамином",
    cashback: "20%",
    checked: false,
  },
];

export default productsData;
